### ISSUE TITLE
Add Index Alias management capabilities

### ISSUE THREAD

**Issue by pierrelambert** [redis/redis-vl-python#162]
The Alias capability of Indexes with ft.aliasadd, ft.aliasdel, FT.ALIASUPDATE permits agility in making index and apps evolving. 
Would be nice to be able to handle this at SearchIndex level directly.

**Comment by tylerhutcherson** [comment]
@pierrelambert 100% Agreed - this is planned for the `0.3.0` release. Though it gets tricky without the ability to list which aliases are used per index. 

Ideally the index alias would be a schema property like this:
```yaml

index:
  name: users_v1
  prefix: user
  alias: users

fields:
    - name: user
      type: tag
    - name: credit_score
      type: tag
```
So then the alias would get added transparently as they call `index.create(...)`

And then a new command to update the alias:

```python
index.update_alias("new_alias_name")
```

However, given we can't trace the state of the index<>alias relationships... this is pretty much impossible without footguns all over the place.

@bsbodden curious on your take?
