### ISSUE TITLE
Incorrect number of embedding dimensions in the YAML schema in README.md 

### ISSUE THREAD

**Issue by mirekphd** [redis/redis-vl-python#204]
The sample schema in the YAML format presented in the `README.md` file in [this](https://github.com/redis/redis-vl-python?tab=readme-ov-file#%EF%B8%8F-redis-index-management) section contains an incorrect number of embedding dimensions in the `dims` key - they should be changed from 3 to 4 to work with the rest of the example.

Published version:
```
index:
[..]
fields:
[..]
    attrs:
      algorithm: flat
      dims: 3
      distance_metric: cosine
      datatype: float32
```
... should be:
```
index:
[..]
fields:
[..]
    attrs:
      algorithm: flat
      dims: 4
      distance_metric: cosine
      datatype: float32
```
